/*
 * Web Application Firewall API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WAFEvents200ResultsInnerTop10CountriesInner
 */
public class WAFEvents200ResultsInnerTop10CountriesInnerTest {
    private final WAFEvents200ResultsInnerTop10CountriesInner model = new WAFEvents200ResultsInnerTop10CountriesInner();

    /**
     * Model tests for WAFEvents200ResultsInnerTop10CountriesInner
     */
    @Test
    public void testWAFEvents200ResultsInnerTop10CountriesInner() {
        // TODO: test WAFEvents200ResultsInnerTop10CountriesInner
    }

}
