/*
 * Edge Firewall API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.GenericBehaviorDetails;
import org.openapitools.client.model.SetRateLimitDetails;
import org.openapitools.client.model.SetWAFRuleSetDetails;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import org.openapitools.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-13T11:40:32.253694Z[GMT]")
public class BehaviorsArgument extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(BehaviorsArgument.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!BehaviorsArgument.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'BehaviorsArgument' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GenericBehaviorDetails> adapterGenericBehaviorDetails = gson.getDelegateAdapter(this, TypeToken.get(GenericBehaviorDetails.class));
            final TypeAdapter<SetRateLimitDetails> adapterSetRateLimitDetails = gson.getDelegateAdapter(this, TypeToken.get(SetRateLimitDetails.class));
            final TypeAdapter<SetWAFRuleSetDetails> adapterSetWAFRuleSetDetails = gson.getDelegateAdapter(this, TypeToken.get(SetWAFRuleSetDetails.class));

            return (TypeAdapter<T>) new TypeAdapter<BehaviorsArgument>() {
                @Override
                public void write(JsonWriter out, BehaviorsArgument value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `GenericBehaviorDetails`
                    if (value.getActualInstance() instanceof GenericBehaviorDetails) {
                      JsonElement element = adapterGenericBehaviorDetails.toJsonTree((GenericBehaviorDetails)value.getActualInstance());
                      elementAdapter.write(out, element);
                      return;
                    }
                    // check if the actual instance is of the type `SetRateLimitDetails`
                    if (value.getActualInstance() instanceof SetRateLimitDetails) {
                      JsonElement element = adapterSetRateLimitDetails.toJsonTree((SetRateLimitDetails)value.getActualInstance());
                      elementAdapter.write(out, element);
                      return;
                    }
                    // check if the actual instance is of the type `SetWAFRuleSetDetails`
                    if (value.getActualInstance() instanceof SetWAFRuleSetDetails) {
                      JsonElement element = adapterSetWAFRuleSetDetails.toJsonTree((SetWAFRuleSetDetails)value.getActualInstance());
                      elementAdapter.write(out, element);
                      return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: GenericBehaviorDetails, SetRateLimitDetails, SetWAFRuleSetDetails");
                }

                @Override
                public BehaviorsArgument read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize GenericBehaviorDetails
                    try {
                      // validate the JSON object to see if any exception is thrown
                      GenericBehaviorDetails.validateJsonElement(jsonElement);
                      actualAdapter = adapterGenericBehaviorDetails;
                      match++;
                      log.log(Level.FINER, "Input data matches schema 'GenericBehaviorDetails'");
                    } catch (Exception e) {
                      // deserialization failed, continue
                      errorMessages.add(String.format("Deserialization for GenericBehaviorDetails failed with `%s`.", e.getMessage()));
                      log.log(Level.FINER, "Input data does not match schema 'GenericBehaviorDetails'", e);
                    }
                    // deserialize SetRateLimitDetails
                    try {
                      // validate the JSON object to see if any exception is thrown
                      SetRateLimitDetails.validateJsonElement(jsonElement);
                      actualAdapter = adapterSetRateLimitDetails;
                      match++;
                      log.log(Level.FINER, "Input data matches schema 'SetRateLimitDetails'");
                    } catch (Exception e) {
                      // deserialization failed, continue
                      errorMessages.add(String.format("Deserialization for SetRateLimitDetails failed with `%s`.", e.getMessage()));
                      log.log(Level.FINER, "Input data does not match schema 'SetRateLimitDetails'", e);
                    }
                    // deserialize SetWAFRuleSetDetails
                    try {
                      // validate the JSON object to see if any exception is thrown
                      SetWAFRuleSetDetails.validateJsonElement(jsonElement);
                      actualAdapter = adapterSetWAFRuleSetDetails;
                      match++;
                      log.log(Level.FINER, "Input data matches schema 'SetWAFRuleSetDetails'");
                    } catch (Exception e) {
                      // deserialization failed, continue
                      errorMessages.add(String.format("Deserialization for SetWAFRuleSetDetails failed with `%s`.", e.getMessage()));
                      log.log(Level.FINER, "Input data does not match schema 'SetWAFRuleSetDetails'", e);
                    }

                    if (match == 1) {
                        BehaviorsArgument ret = new BehaviorsArgument();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for BehaviorsArgument: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public BehaviorsArgument() {
        super("oneOf", Boolean.FALSE);
    }

    public BehaviorsArgument(GenericBehaviorDetails o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public BehaviorsArgument(SetRateLimitDetails o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public BehaviorsArgument(SetWAFRuleSetDetails o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("GenericBehaviorDetails", GenericBehaviorDetails.class);
        schemas.put("SetRateLimitDetails", SetRateLimitDetails.class);
        schemas.put("SetWAFRuleSetDetails", SetWAFRuleSetDetails.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return BehaviorsArgument.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * GenericBehaviorDetails, SetRateLimitDetails, SetWAFRuleSetDetails
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof GenericBehaviorDetails) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof SetRateLimitDetails) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof SetWAFRuleSetDetails) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be GenericBehaviorDetails, SetRateLimitDetails, SetWAFRuleSetDetails");
    }

    /**
     * Get the actual instance, which can be the following:
     * GenericBehaviorDetails, SetRateLimitDetails, SetWAFRuleSetDetails
     *
     * @return The actual instance (GenericBehaviorDetails, SetRateLimitDetails, SetWAFRuleSetDetails)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `GenericBehaviorDetails`. If the actual instance is not `GenericBehaviorDetails`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `GenericBehaviorDetails`
     * @throws ClassCastException if the instance is not `GenericBehaviorDetails`
     */
    public GenericBehaviorDetails getGenericBehaviorDetails() throws ClassCastException {
        return (GenericBehaviorDetails)super.getActualInstance();
    }
    /**
     * Get the actual instance of `SetRateLimitDetails`. If the actual instance is not `SetRateLimitDetails`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SetRateLimitDetails`
     * @throws ClassCastException if the instance is not `SetRateLimitDetails`
     */
    public SetRateLimitDetails getSetRateLimitDetails() throws ClassCastException {
        return (SetRateLimitDetails)super.getActualInstance();
    }
    /**
     * Get the actual instance of `SetWAFRuleSetDetails`. If the actual instance is not `SetWAFRuleSetDetails`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SetWAFRuleSetDetails`
     * @throws ClassCastException if the instance is not `SetWAFRuleSetDetails`
     */
    public SetWAFRuleSetDetails getSetWAFRuleSetDetails() throws ClassCastException {
        return (SetWAFRuleSetDetails)super.getActualInstance();
    }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to BehaviorsArgument
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    // validate oneOf schemas one by one
    int validCount = 0;
    ArrayList<String> errorMessages = new ArrayList<>();
    // validate the json string with GenericBehaviorDetails
    try {
      GenericBehaviorDetails.validateJsonElement(jsonElement);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for GenericBehaviorDetails failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    // validate the json string with SetRateLimitDetails
    try {
      SetRateLimitDetails.validateJsonElement(jsonElement);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for SetRateLimitDetails failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    // validate the json string with SetWAFRuleSetDetails
    try {
      SetWAFRuleSetDetails.validateJsonElement(jsonElement);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for SetWAFRuleSetDetails failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    if (validCount != 1) {
      throw new IOException(String.format("The JSON string is invalid for BehaviorsArgument with oneOf schemas: GenericBehaviorDetails, SetRateLimitDetails, SetWAFRuleSetDetails. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
    }
  }

 /**
  * Create an instance of BehaviorsArgument given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BehaviorsArgument
  * @throws IOException if the JSON string is invalid with respect to BehaviorsArgument
  */
  public static BehaviorsArgument fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BehaviorsArgument.class);
  }

 /**
  * Convert an instance of BehaviorsArgument to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

