/*
 * Edge Application API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.client.model.RulesEngineBehaviorTargetOneOf;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RulesEngineBehaviorTarget
 */
public class RulesEngineBehaviorTargetTest {
    private final RulesEngineBehaviorTarget model = new RulesEngineBehaviorTarget();

    /**
     * Model tests for RulesEngineBehaviorTarget
     */
    @Test
    public void testRulesEngineBehaviorTarget() {
        // TODO: test RulesEngineBehaviorTarget
    }

    /**
     * Test the property 'capturedArray'
     */
    @Test
    public void capturedArrayTest() {
        // TODO: test capturedArray
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'regex'
     */
    @Test
    public void regexTest() {
        // TODO: test regex
    }

}
