/*
 * Digital Certificates API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CreateCSRRequest;
import org.openapitools.client.model.DC201;
import org.openapitools.client.model.DC400;
import org.openapitools.client.model.DC403;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CreateCsrApi
 */
@Disabled
public class CreateCsrApiTest {

    private final CreateCsrApi api = new CreateCsrApi();

    /**
     * Create an encrypted Certificate Request with Azion, which can then be sent for signing to a CA
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createCSRTest() throws ApiException {
        CreateCSRRequest createCSRRequest = null;
        DC201 response = api.createCSR(createCSRRequest);
        // TODO: test validations
    }

}
