/*
 * Digital Certificates API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CreateCertificateRequest;
import org.openapitools.client.model.DC201;
import org.openapitools.client.model.DC400;
import org.openapitools.client.model.DC403;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CreateDigitalCertificateApi
 */
@Disabled
public class CreateDigitalCertificateApiTest {

    private final CreateDigitalCertificateApi api = new CreateDigitalCertificateApi();

    /**
     * Create a new digital certificate
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createCertificateTest() throws ApiException {
        CreateCertificateRequest createCertificateRequest = null;
        DC201 response = api.createCertificate(createCertificateRequest);
        // TODO: test validations
    }

}
