/*
 * Purge API
 * Azion Real-Time Purge
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.PurgeCacheKeyRequest;
import org.openapitools.client.model.PurgeUrlRequest;
import org.openapitools.client.model.PurgeWildcardRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RealTimePurgeApi
 */
@Disabled
public class RealTimePurgeApiTest {

    private final RealTimePurgeApi api = new RealTimePurgeApi();

    /**
     * /purge/cachekey
     *
     * List of Cache Keys you want to remove from the Azion Edge Servers cache.  urls (array): list of up to 50 Cache Keys to be expired from the cache, per request.  method (choice): purge method, use the “delete” value for removal.  Layer (choice): layer where the purge will be done. Use the value “edge_caching” (default value if not informed) to purge on the Edge Caching layer and the value “l2_caching” to purge on L2 Caching.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void purgeCacheKeyTest() throws ApiException {
        String accept = null;
        String contentType = null;
        PurgeCacheKeyRequest purgeCacheKeyRequest = null;
        api.purgeCacheKey(accept, contentType, purgeCacheKeyRequest);
        // TODO: test validations
    }

    /**
     * /purge/url
     *
     * List of URLs you want to remove from the Azion Edge Servers cache.  urls (array): list of up to 50 URLs to be expired from the cache, per request.  method (choice): purge method, use the “delete” value for removal.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void purgeUrlTest() throws ApiException {
        String accept = null;
        String contentType = null;
        PurgeUrlRequest purgeUrlRequest = null;
        api.purgeUrl(accept, contentType, purgeUrlRequest);
        // TODO: test validations
    }

    /**
     * /purge/wildcard
     *
     * The Wildcard expression that represents the list of objects that you want to remove from the Azion Edge Servers cache.  urls (array):the Wildcard URL or Wildcard Cache Key that represents the list of objects you want to expire. You can only use one Wildcard expression per request.  method (choice): purge method, use the “delete” value for removal.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void purgeWildcardTest() throws ApiException {
        String accept = null;
        String contentType = null;
        PurgeWildcardRequest purgeWildcardRequest = null;
        api.purgeWildcard(accept, contentType, purgeWildcardRequest);
        // TODO: test validations
    }

}
