/*
 * Edge Firewall API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.SetRateLimitBehaviorArgument;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SetRateLimitBehavior
 */
public class SetRateLimitBehaviorTest {
    private final SetRateLimitBehavior model = new SetRateLimitBehavior();

    /**
     * Model tests for SetRateLimitBehavior
     */
    @Test
    public void testSetRateLimitBehavior() {
        // TODO: test SetRateLimitBehavior
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'argument'
     */
    @Test
    public void argumentTest() {
        // TODO: test argument
    }

}
