/*
 * Network Lists API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for NetworkListUuidResponseEntryString
 */
public class NetworkListUuidResponseEntryStringTest {
    private final NetworkListUuidResponseEntryString model = new NetworkListUuidResponseEntryString();

    /**
     * Model tests for NetworkListUuidResponseEntryString
     */
    @Test
    public void testNetworkListUuidResponseEntryString() {
        // TODO: test NetworkListUuidResponseEntryString
    }

    /**
     * Test the property 'lastEditor'
     */
    @Test
    public void lastEditorTest() {
        // TODO: test lastEditor
    }

    /**
     * Test the property 'lastModified'
     */
    @Test
    public void lastModifiedTest() {
        // TODO: test lastModified
    }

    /**
     * Test the property 'listType'
     */
    @Test
    public void listTypeTest() {
        // TODO: test listType
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'itemsValues'
     */
    @Test
    public void itemsValuesTest() {
        // TODO: test itemsValues
    }

}
