/*
 * Data Streaming - OpenAPI
 * The Data Streaming API allows you to manage your existing data streamings and templates. Data Streaming allows you to feed your stream processing, SIEM, and big data platforms with the event logs from your applications on Azion in real time. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EndpoinrtS3
 */
public class EndpoinrtS3Test {
    private final EndpoinrtS3 model = new EndpoinrtS3();

    /**
     * Model tests for EndpoinrtS3
     */
    @Test
    public void testEndpoinrtS3() {
        // TODO: test EndpoinrtS3
    }

    /**
     * Test the property 'endpointType'
     */
    @Test
    public void endpointTypeTest() {
        // TODO: test endpointType
    }

    /**
     * Test the property 'accessKey'
     */
    @Test
    public void accessKeyTest() {
        // TODO: test accessKey
    }

    /**
     * Test the property 'region'
     */
    @Test
    public void regionTest() {
        // TODO: test region
    }

    /**
     * Test the property 'objectKeyPrefix'
     */
    @Test
    public void objectKeyPrefixTest() {
        // TODO: test objectKeyPrefix
    }

    /**
     * Test the property 'bucketName'
     */
    @Test
    public void bucketNameTest() {
        // TODO: test bucketName
    }

    /**
     * Test the property 'contentType'
     */
    @Test
    public void contentTypeTest() {
        // TODO: test contentType
    }

    /**
     * Test the property 'hostUrl'
     */
    @Test
    public void hostUrlTest() {
        // TODO: test hostUrl
    }

    /**
     * Test the property 'secretKey'
     */
    @Test
    public void secretKeyTest() {
        // TODO: test secretKey
    }

}
